### PR TITLE
Fixes: #7 -add performance comparison to readme

### PR DESCRIPTION
**Pull request by banagale**
Some changes to handle #7.

- Surfaces key benchmark data to readme, cleans up file whitespace
- Adds table with relative performance and semi-sorted raw data

I wasn't sure if you needed the docs regenerated, or would do that as part of a release.

### CODE REVIEW

**Comment by Mng-dev-ai** [comment]
It's great but there's only one thing I need you to change : 

>  drf-turbo performs serialization nearly

drf-turbo is not only for serialization, It's also for deserialization and validation

**Comment by banagale** [comment]
Thanks for that note. I will need to dig into the benchmark tests and do some implementations to get to know the library better.

I made the requested change and a few more. Feel free to offer more feedback.

**Comment by Mng-dev-ai** [comment]
Also here : 

> `drf-turbo` serialization performance averages 86% faster than DRF's standard serializer.

**Comment by banagale** [comment]
Got it.

**Pull request merged**
